//CommonJS,every file is module(by default)
//Modules-Encapsulated Code(only share minimum)
const names=require('./4-names')
const sayhi=require('./5-utils')
const data=require('./6-alternative-flav')
require('./7-mind-granade')
// sayhi('susan')
// sayhi(names.hrish)
// sayhi(names.dish)
